/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Layout: typeof import('./../../src/components/layout/layout.vue')['default']
    LayoutHeader: typeof import('./../../src/components/layout/layout-header.vue')['default']
    LayoutMain: typeof import('./../../src/components/layout/layout-main.vue')['default']
    LayoutMenuItem: typeof import('./../../src/components/layout/layout-menu-item.vue')['default']
    LayoutMenus: typeof import('./../../src/components/layout/layout-menus.vue')['default']
    LayoutSidebar: typeof import('./../../src/components/layout/layout-sidebar.vue')['default']
    Loading: typeof import('./../../src/components/Loading/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
